% compile the MEX code.

cmd = ['mex mex/precond_mex.cpp ' ...
       'mex/forest/forest_precondition.cpp ' ...
       'mex/forest/tree.cc '          ...
       'mex/forest/tree_node.cc '     ...
       'mex/pairing_heap/break_point.cc '   ...
       '-largeArrayDims -lboost_serialization -v ' ...
       'CXXFLAGS=''$CXXFLAGS -fopenmp -O3'' CFLAGS=''\$CFLAGS -fopenmp -O3'' LDFLAGS=''\$LDFLAGS -fopenmp'' '];
eval(cmd);

